/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package All_Forms;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import library.Not_Exists;
import library.std;

/**
 *
 * @author Library
 */
public class Book_Doesnt_exsist extends javax.swing.JFrame {

    /**
     * Creates new form Book_Doesnt_exsist
     */
    public Book_Doesnt_exsist() {
        super("المكتبة الرقمية");
        initComponents();
        show_information_in_JTable();
    }
    public static String url = "";
    public static Connection con;

    public static void SetURL() {
        url = "jdbc:mysql://localhost:3306/library"
                + "?useUnicode=true&characterEncoding=UTF-8";
    }

    public Connection getConnection() {
        try {
            SetURL();
            con = DriverManager.getConnection(url, "root", "");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        return con;
    }

    public ArrayList<Not_Exists> getuserlist() {
        ArrayList<Not_Exists> userList = new ArrayList<>();
        Connection connection = getConnection();
        String query = "select * from book , add_emprunt where bookno = add_emprunt.book_no ";
        Statement st;
        ResultSet rs;
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            Not_Exists ne;
            while (rs.next()) {
                ne = new Not_Exists(rs.getInt("book_id"), rs.getString("bookname"), rs.getInt("bookno"), rs.getString("creator"), rs.getDate("cr_date"), rs.getString("house"), rs.getString("book_spc"), rs.getBytes("book_img"), rs.getString("img_path"));
                userList.add(ne);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        return userList;
    }

    public void show_information_in_JTable() {
        ArrayList<Not_Exists> list = getuserlist();
        DefaultTableModel f = (DefaultTableModel) book_not_exsist.getModel();
        Object obj[] = new Object[7];
        for (int x = 0; x < list.size(); x++) {
            obj[0] = list.get(x).getSpc();
            obj[1] = list.get(x).getHouse();
            obj[2] = list.get(x).getCr_date();
            obj[3] = list.get(x).getCreator();
            obj[4] = list.get(x).getBookno();
            obj[5] = list.get(x).getBookname();
            obj[6] = list.get(x).getId();
            f.addRow(obj);
        }
    }

    public void executeSQlQuery(String query) {
        Connection con = getConnection();
        Statement st;
        try {
            st = con.createStatement();
            st.executeUpdate(query);
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        book_not_exsist = new javax.swing.JTable();
        rSPanelsSlider1 = new rojeru_san.RSPanelsSlider();
        jLabel1 = new javax.swing.JLabel();
        rSButtonRiple1 = new rojeru_san.RSButtonRiple();
        jLabel4 = new javax.swing.JLabel();
        btnname = new javax.swing.JRadioButton();
        btnno = new javax.swing.JRadioButton();
        btncreator = new javax.swing.JRadioButton();
        btnhouse = new javax.swing.JRadioButton();
        rspc = new javax.swing.JRadioButton();
        txtsearch = new Tools_For_Form.JTextBox(25);
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_date = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txt_house = new Tools_For_Form.JTextBox(15);
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_spc = new Tools_For_Form.JTextBox(15);
        txt_book_number = new Tools_For_Form.JTextBox(15);
        txt_book_name = new Tools_For_Form.JTextBox(15);
        txt_book_no = new Tools_For_Form.JTextBox(15);
        txt_creator_name = new Tools_For_Form.JTextBox(15);
        lbl_img_book1 = new javax.swing.JLabel();
        book_img_path1 = new javax.swing.JLabel();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        book_not_exsist.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        book_not_exsist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "التخصص", "دار النشر", "تاريخ الإصدار", "إسم المِِِؤلف", "رقم الكتاب", "إسم الكتاب", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        book_not_exsist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                book_not_exsistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(book_not_exsist);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("الكتب المستعارة");
        rSPanelsSlider1.add(jLabel1, "card2");

        rSButtonRiple1.setText("PrintJtable");
        rSButtonRiple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Rechercher Par :");

        btnname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnname.setText("إسم الكتاب");
        btnname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnameActionPerformed(evt);
            }
        });

        btnno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnno.setText("رقم الكتاب");

        btncreator.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btncreator.setText("إسم المؤلف");

        btnhouse.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnhouse.setText("دار النشر");
        btnhouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhouseActionPerformed(evt);
            }
        });

        rspc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rspc.setText("الإختصاص");
        rspc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rspcActionPerformed(evt);
            }
        });

        txtsearch.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        txtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchMouseClicked(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informtion sur les livres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel2.setText("اسم الكتاب :");

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel3.setText("رقم الكتاب :");

        jLabel5.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel5.setText("إسم المؤلف:");

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel6.setText("تاريخ الإنشاء:");

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel7.setText("الكتاب رقم:");

        txt_date.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel8.setText("دار النشر:");

        txt_house.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_house.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_house.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_houseActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel11.setText("صورة الكتاب");

        jLabel12.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel12.setText("الإختصاص:");

        txt_spc.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_spc.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_book_number.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_book_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_book_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_book_numberActionPerformed(evt);
            }
        });

        txt_book_name.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_book_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_book_no.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_book_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_creator_name.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_creator_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(txt_book_number)
                    .addComponent(txt_book_name)
                    .addComponent(txt_book_no)
                    .addComponent(txt_creator_name))
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(1, 1, 1))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl_img_book1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txt_house, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addComponent(txt_spc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(book_img_path1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(0, 48, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_book_number, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_book_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_book_no)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_creator_name))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lbl_img_book1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(book_img_path1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txt_house, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_spc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnname, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnno)
                        .addGap(18, 18, 18)
                        .addComponent(btncreator)
                        .addGap(18, 18, 18)
                        .addComponent(btnhouse)
                        .addGap(18, 18, 18)
                        .addComponent(rspc)
                        .addGap(18, 18, 18)
                        .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(398, 398, 398)
                .addComponent(rSButtonRiple1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(937, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(rSPanelsSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnname)
                    .addComponent(btnno)
                    .addComponent(btncreator)
                    .addComponent(btnhouse)
                    .addComponent(rspc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(rSButtonRiple1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnameActionPerformed

    private void btnhouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhouseActionPerformed

    private void rspcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rspcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rspcActionPerformed

    private void txtsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseClicked
        // TODO addtxt_book_nameing code here:
    }//GEN-LAST:event_txtsearchMouseClicked

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        if (btnname.isSelected()) {
            try {
                Not_Exists b = new Not_Exists();
                String search = " bookname like'%" + txtsearch.getText() + "%'";
                b.searchinfo(search, book_not_exsist);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else if (btnno.isSelected()) {
            try {
                Not_Exists b = new Not_Exists();
                String search = " bookno like'%" + txtsearch.getText() + "%'";
                b.searchinfo(search, book_not_exsist);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else if (btncreator.isSelected()) {
            try {
                Not_Exists b = new Not_Exists();
                String search = " creator like'%" + txtsearch.getText() + "%'";
                b.searchinfo(search, book_not_exsist);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else if (btnhouse.isSelected()) {
            try {
                Not_Exists b = new Not_Exists();
                String search = "book where house like'%" + txtsearch.getText() + "%'";
                b.searchinfo(search, book_not_exsist);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else if (rspc.isSelected()) {
            try {
                Not_Exists b = new Not_Exists();
                String search = " book_spc like'%" + txtsearch.getText() + "%'";
                b.searchinfo(search, book_not_exsist);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "الرجاء تحديد نمط البحث");
            txtsearch.setText("");
        }

        //        String search = " book where ";
        //        if (rno.isSelected()) {
        //            search += "booko";
        //        } else {                                                        ///////////// هاذي باش تخير اذا تروشارشي بالاسم ولا بالرقم الخاص بالكتاب
        //            search += "bookname";
        //        }
        //        search += " like'%" + txtsearch.getText() + "%'";
        //        b.searchinfo(search, tblbook);
        //        txtsearch.requestFocus();
        //        showselectedrow();
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txt_houseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_houseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_houseActionPerformed

    private void txt_book_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_book_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_book_numberActionPerformed
    ResultSet rs;
    PreparedStatement ps;
    String table_clicked;
    private void book_not_exsistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_book_not_exsistMouseClicked
        // TODO add your handling code here:
        int row = book_not_exsist.getSelectedRow();
        table_clicked = (book_not_exsist.getValueAt(row, 6).toString());
        int table_Id = Integer.parseInt(table_clicked);
        String Query = "SELECT * FROM `book` WHERE `book_id` =" + table_clicked;
        try {
            ps = getConnection().prepareStatement(Query);
            rs = ps.executeQuery();
            if (rs.next()) {
                String id = rs.getString("book_id");
                txt_book_number.setText(id);

                String title = rs.getString("bookname");
                txt_book_name.setText(title);

                String bookno = rs.getString("bookno");
                txt_book_no.setText(bookno);

                String creator_name = rs.getString("creator");
                txt_creator_name.setText(creator_name);

                Date cr_date = rs.getDate("cr_date");
                txt_date.setDate(cr_date);

                String bookImgPath = rs.getString("img_path");
                book_img_path1.setText(bookImgPath);

                String Dar_Nashr = rs.getString("house");
                txt_house.setText(Dar_Nashr);

                String Spc = rs.getString("book_spc");
                txt_spc.setText(Spc);

                byte[] std_Image = rs.getBytes("book_img");
                ImageIcon imgicon = new ImageIcon(new ImageIcon(std_Image).getImage().getScaledInstance(lbl_img_book1.getWidth(), lbl_img_book1.getHeight(), Image.SCALE_SMOOTH));
                lbl_img_book1.setIcon(imgicon);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_book_not_exsistMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        book_not_exsist.getTableHeader().setReorderingAllowed(false);
        book_not_exsist.getTableHeader().setBackground(new Color(0, 153, 255));

        txt_book_number.setEditable(false);
        txt_book_name.setEditable(false);
        txt_book_no.setEditable(false);
        txt_creator_name.setEditable(false);
        txt_date.setEnabled(false);
        txt_house.setEditable(false);
        txt_spc.setEditable(false);
        book_img_path1.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void rSButtonRiple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple1ActionPerformed
        // TODO add your handling code here:
         MessageFormat h = new MessageFormat("قائمة الكتب الموجودة في المكتبة");
        try {
            book_not_exsist.print(JTable.PrintMode.FIT_WIDTH, h, new MessageFormat(""));
        } catch (PrinterException ex) {
            Logger.getLogger(Book_form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rSButtonRiple1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Book_Doesnt_exsist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Book_Doesnt_exsist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Book_Doesnt_exsist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Book_Doesnt_exsist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Book_Doesnt_exsist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book_img_path1;
    private javax.swing.JTable book_not_exsist;
    private javax.swing.JRadioButton btncreator;
    private javax.swing.JRadioButton btnhouse;
    private javax.swing.JRadioButton btnname;
    private javax.swing.JRadioButton btnno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_img_book1;
    private rojeru_san.RSButtonRiple rSButtonRiple1;
    private rojeru_san.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JRadioButton rspc;
    private javax.swing.JTextField txt_book_name;
    private javax.swing.JTextField txt_book_no;
    private javax.swing.JTextField txt_book_number;
    private javax.swing.JTextField txt_creator_name;
    private com.toedter.calendar.JDateChooser txt_date;
    private javax.swing.JTextField txt_house;
    private javax.swing.JTextField txt_spc;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables
}
