/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package All_Forms;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import library.books;

/**
 *
 * @author DataBase
 */
public class Student_Form extends javax.swing.JFrame {

    /**
     * Creates new form Book_form
     */
    public ArrayList<books> getuserlist() {
        ArrayList<books> userList = new ArrayList<>();
        Connection connection = getConnection();
        String query = "select * from book";
        Statement st;
        ResultSet rs;
        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            books book;
            while (rs.next()) {
                book = new books(rs.getInt("book_id"), rs.getString("bookname"), rs.getInt("bookno"), rs.getDate("cr_date"), rs.getString("creator"), rs.getString("house"), rs.getString("book_spc"), rs.getBytes("book_img"), rs.getString("img_path"));
                userList.add(book);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        return userList;
    }

    public void show_information_in_JTable() {
        ArrayList<books> list = getuserlist();
        DefaultTableModel f = (DefaultTableModel) tblbook.getModel();
        Object obj[] = new Object[8];
        for (int x = 0; x < list.size(); x++) {
            //  obj[0] = list.get(x).getImage_path();
            obj[0] = list.get(x).getSpc();
            obj[1] = list.get(x).getHouse();
            obj[2] = list.get(x).getCreator();
            obj[3] = list.get(x).getCr_date();
            obj[4] = list.get(x).getBookno();
            obj[5] = list.get(x).getBookname();
            obj[6] = list.get(x).getId();

            f.addRow(obj);
        }
    }

    public Student_Form() {
        super("المكتبة الرقمية");
        initComponents();
        show_information_in_JTable();
        ShowDate();
        ShowTime();
    }

    public void executeSQlQuery(String query) {
        Connection con = getConnection();
        Statement st;
        try {
            st = con.createStatement();
            if (st.executeUpdate(query) == 1) {
                ClearText();
            } else {
                ClearText();
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnall = new javax.swing.ButtonGroup();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtsearch = new Tools_For_Form.JTextBox(25);
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_date = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txt_house = new Tools_For_Form.JTextBox(15);
        lbl_img_book = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_spc = new Tools_For_Form.JTextBox(15);
        book_img_path = new javax.swing.JLabel();
        txt_book_number = new Tools_For_Form.JTextBox(15);
        txt_book_name = new Tools_For_Form.JTextBox(15);
        txt_book_no = new Tools_For_Form.JTextBox(15);
        txt_creator_name = new Tools_For_Form.JTextBox(15);
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbook = new javax.swing.JTable();
        rSButtonRiple5 = new rojeru_san.RSButtonRiple();
        jLabel4 = new javax.swing.JLabel();
        btnname = new javax.swing.JRadioButton();
        btnno = new javax.swing.JRadioButton();
        btncreator = new javax.swing.JRadioButton();
        btnhouse = new javax.swing.JRadioButton();
        rspc = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Orator Std", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 204));
        jLabel9.setText("Gestion la Bibliotheque ");

        jLabel10.setFont(new java.awt.Font("Orator Std", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 204));
        jLabel10.setText("Lycce Houcine Ait Ahmed -souidania- ");

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        date.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        time.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(542, 542, 542)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        txtsearch.setFont(new java.awt.Font("Andalus", 1, 12)); // NOI18N
        txtsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtsearchMouseClicked(evt);
            }
        });
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        jLabel5.setFont(new java.awt.Font("Orator Std", 3, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("GESTION DES LIVRES");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(855, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informtion sur les livres", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel5.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel1.setText("اسم الكتاب :");

        jLabel2.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel2.setText("رقم الكتاب :");

        jLabel3.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel3.setText("إسم المؤلف:");

        jLabel6.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel6.setText("تاريخ الإنشاء:");

        jLabel7.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel7.setText("الكتاب رقم:");

        txt_date.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel8.setText("دار النشر:");

        txt_house.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_house.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_house.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_houseActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel11.setText("صورة الكتاب");

        jLabel12.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        jLabel12.setText("الإختصاص:");

        txt_spc.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_spc.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_book_number.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_book_number.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_book_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_book_numberActionPerformed(evt);
            }
        });

        txt_book_name.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_book_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_book_no.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_book_no.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txt_creator_name.setFont(new java.awt.Font("Andalus", 1, 18)); // NOI18N
        txt_creator_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_date, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(txt_book_number)
                            .addComponent(txt_book_name)
                            .addComponent(txt_book_no)
                            .addComponent(txt_creator_name))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7))
                                .addGap(1, 1, 1))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_img_book, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(75, 75, 75))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addComponent(book_img_path, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_house, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(26, 26, 26)
                        .addComponent(txt_spc, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel12)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_house, txt_spc});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_book_number, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_book_name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_book_no)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_creator_name))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_img_book, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(book_img_path, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txt_house, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_spc, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txt_house, txt_spc});

        tblbook.setFont(new java.awt.Font("Andalus", 1, 14)); // NOI18N
        tblbook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الإختصاص", "دار النشر", "إسم المؤلف", "تاريخ الإصدار", "رقم الكتاب", "إسم الكتاب", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblbookMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblbook);

        rSButtonRiple5.setBackground(new java.awt.Color(204, 0, 0));
        rSButtonRiple5.setText("Quitter");
        rSButtonRiple5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple5ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Rechercher Par :");

        btnname.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnname.setText("إسم الكتاب");
        btnname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnameActionPerformed(evt);
            }
        });

        btnno.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnno.setText("رقم الكتاب");

        btncreator.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btncreator.setText("إسم المؤلف");

        btnhouse.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnhouse.setText("دار النشر");
        btnhouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhouseActionPerformed(evt);
            }
        });

        rspc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        rspc.setText("الإختصاص");
        rspc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rspcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(rSButtonRiple5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnname, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnno)
                .addGap(18, 18, 18)
                .addComponent(btncreator)
                .addGap(18, 18, 18)
                .addComponent(btnhouse)
                .addGap(18, 18, 18)
                .addComponent(rspc)
                .addGap(63, 63, 63)
                .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnname)
                    .addComponent(btnno)
                    .addComponent(btncreator)
                    .addComponent(btnhouse)
                    .addComponent(rspc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSButtonRiple5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(1598, 719));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public static String url;
    public static Connection con;

    public static void SetURL() {
        url = "jdbc:mysql://localhost:3306/library"
                + "?useUnicode=true&characterEncoding=UTF-8";
    }

    public void ShowDate() {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-YYYY");
        date.setText(sdf.format(d));
    }

    public void ShowTime() {
        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss a");
                time.setText(sdf.format(d));
            }
        }).start();

    }

    public Connection getConnection() {
        try {
            SetURL();
            con = DriverManager.getConnection(url, "root", "");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        return con;
    }

    public void executeSQlQuery(String query, String Message) {
        Connection con = getConnection();
        Statement st;
        try {
            st = con.createStatement();
            if (st.executeUpdate(query) == 1) {
                JOptionPane.showMessageDialog(null, "تم " + Message + "بنجاح ");
            } else {
                JOptionPane.showMessageDialog(null, "لم يتم " + Message);

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    public void ClearText() {
        txt_book_name.setText("");
        txt_book_no.setText("");
        txt_creator_name.setText("");
        txt_book_name.requestFocus();
    }

    public void showselectedrow() {

        int i = tblbook.getSelectedRow();
        TableModel model = tblbook.getModel();
        txt_book_number.setText(model.getValueAt(i, 6).toString());
        txt_book_name.setText(model.getValueAt(i, 5).toString());
        txt_book_no.setText(model.getValueAt(i, 4).toString());
        txt_date.setDate((Date) model.getValueAt(i, 3));
        txt_creator_name.setText(model.getValueAt(i, 2).toString());
        txt_house.setText(model.getValueAt(i, 1).toString());
        txt_spc.setText(model.getValueAt(i, 0).toString());
        byte[] img = (getuserlist().get(i).getImg());
        ImageIcon imgicon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img_book.getWidth(), lbl_img_book.getHeight(), Image.SCALE_SMOOTH));
        lbl_img_book.setIcon(imgicon);
        String img_path = (getuserlist().get(i).getImage_path());
        book_img_path.setText(img_path);

    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txt_book_number.setEditable(false);
        txt_book_name.setEditable(false);
        txt_book_no.setEditable(false);
        txt_creator_name.setEditable(false);
        txt_date.setEnabled(false);
        txt_house.setEditable(false);
        txt_spc.setEditable(false);
//        book_img_path.setVisible(false);

        try {
            Image img = ImageIO.read(getClass().getResource("library.jpg"));
            this.setIconImage(img);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        tblbook.getTableHeader().setReorderingAllowed(false);
        tblbook.getTableHeader().setBackground(new Color(0, 153, 255));

        btnall.add(btnname);
        btnall.add(btncreator);
        btnall.add(btnno);
        btnall.add(btnhouse);
        btnall.add(rspc);

    }//GEN-LAST:event_formWindowOpened

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        if (btnname.isSelected()) {
            try {
                books b = new books();
                String search = "book where bookname like'%" + txtsearch.getText() + "%'";
                b.StudentSearchBook(search, tblbook); ///////هاذا الكود لقديم لي كنت دايرو  (تروشارشي غير باسم الكتاب )                                          
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else if (btnno.isSelected()) {
            try {
                books b = new books();
                String search = "book where bookno like'%" + txtsearch.getText() + "%'";
                b.StudentSearchBook(search, tblbook);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else if (btncreator.isSelected()) {
            try {
                books b = new books();
                String search = "book where creator like'%" + txtsearch.getText() + "%'";
                b.StudentSearchBook(search, tblbook);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else if (btnhouse.isSelected()) {
            try {
                books b = new books();
                String search = "book where house like'%" + txtsearch.getText() + "%'";
                b.StudentSearchBook(search, tblbook);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else if (rspc.isSelected()) {
            try {
                books b = new books();
                String search = "book where book_spc like'%" + txtsearch.getText() + "%'";
                b.StudentSearchBook(search, tblbook);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "الرجاء تحديد نمط البحث");
            txtsearch.setText("");
        }

        //        String search = " book where ";
        //        if (rno.isSelected()) {
        //            search += "booko";
        //        } else {                                                        ///////////// هاذي باش تخير اذا تروشارشي بالاسم ولا بالرقم الخاص بالكتاب
        //            search += "bookname";
        //        }
        //        search += " like'%" + txtsearch.getText() + "%'";
        //        b.searchinfo(search, tblbook);
        //        txtsearch.requestFocus();
        //        showselectedrow();
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void txtsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtsearchMouseClicked
        // TODO addtxt_book_nameing code here:

    }//GEN-LAST:event_txtsearchMouseClicked
    public String table_clicked;
    public PreparedStatement ps;
    public ResultSet rs;
    private void tblbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblbookMouseClicked
        // TODO add your handling code here:
        int row = tblbook.getSelectedRow();
        table_clicked = (tblbook.getValueAt(row, 6).toString());
        int table_Id = Integer.parseInt(table_clicked);
        String Query = "SELECT * FROM `book` WHERE `book_id` =" + table_clicked;
        try {
            ps = getConnection().prepareStatement(Query);
            rs = ps.executeQuery();
            if (rs.next()) {
                String id = rs.getString("book_id");
                txt_book_number.setText(id);

                String book = rs.getString("bookname");
                txt_book_name.setText(book);

                String bookno = rs.getString("bookno");
                txt_book_no.setText(bookno);

                String creator = rs.getString("creator");
                txt_creator_name.setText(creator);

                String house = rs.getString("house");
                txt_house.setText(house);

                Date cr_date = rs.getDate("cr_date");
                txt_date.setDate(cr_date);

                String spc = rs.getString("book_spc");
                txt_spc.setText(spc);

             
                byte[] std_Image = rs.getBytes("book_img");
                ImageIcon imgicon = new ImageIcon(new ImageIcon(std_Image).getImage().getScaledInstance(lbl_img_book.getWidth(), lbl_img_book.getHeight(), Image.SCALE_SMOOTH));
                lbl_img_book.setIcon(imgicon);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }
//        showselectedrow();
    }//GEN-LAST:event_tblbookMouseClicked
    Edit_book Edit = new Edit_book();
    private void btnnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnameActionPerformed

    private void txt_houseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_houseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_houseActionPerformed

    private void txt_book_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_book_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_book_numberActionPerformed

    private void rspcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rspcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rspcActionPerformed

    private void btnhouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhouseActionPerformed

    private void rSButtonRiple5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        My_Choice m = new My_Choice();
        m.setLocationRelativeTo(null);
        m.setVisible(true);
//        System.exit(0);

    }//GEN-LAST:event_rSButtonRiple5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Form.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book_img_path;
    private javax.swing.ButtonGroup btnall;
    private javax.swing.JRadioButton btncreator;
    private javax.swing.JRadioButton btnhouse;
    private javax.swing.JRadioButton btnname;
    private javax.swing.JRadioButton btnno;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_img_book;
    private rojeru_san.RSButtonRiple rSButtonRiple5;
    private javax.swing.JRadioButton rspc;
    private javax.swing.JTable tblbook;
    private javax.swing.JLabel time;
    private javax.swing.JTextField txt_book_name;
    private javax.swing.JTextField txt_book_no;
    private javax.swing.JTextField txt_book_number;
    private javax.swing.JTextField txt_creator_name;
    private com.toedter.calendar.JDateChooser txt_date;
    private javax.swing.JTextField txt_house;
    private javax.swing.JTextField txt_spc;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

}
